# Generated by Django 5.2.4 on 2025-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("👤", "Default"),
                    ("😊", "Happy"),
                    ("🤓", "Nerd"),
                    ("😎", "Cool"),
                    ("🚀", "Rocket"),
                    ("⭐", "Star"),
                    ("🎯", "Target"),
                    ("💼", "Business"),
                    ("🎨", "Creative"),
                    ("🔥", "Fire"),
                ],
                default="👤",
                max_length=10,
            ),
        ),
    ]
