# Generated by Django 5.2.4 on 2025-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
